package me.biocomp.hubitat_ci.api.device_api.zwave.commands.sensormultilevelv11

import me.biocomp.hubitat_ci.api.device_api.zwave.Command

trait SensorMultilevelSupportedSensorReport implements Command
{
    Boolean accelerationX
    Boolean accelerationY
    Boolean accelerationZ
    Boolean airFlow
    Boolean airTemperature
    Boolean ammoniaLevel
    Boolean anglePosition
    Boolean appliedForce
    Boolean atmosphericPressure
    Boolean barometricPressure
    Boolean bloodPressure
    Boolean bodyMass
    Boolean bodyMassIndex
    Boolean boilerWaterTemperature
    Boolean boneMass
    Boolean carbonDioxideLevel
    Boolean carbonMonoxideLevel
    Boolean condenserCoilTemperature
    Boolean current
    Boolean defrostTemperature
    Boolean dewPoint
    Boolean direction
    Boolean dischargeLinePressure
    Boolean dischargeLineTemperature
    Boolean distance
    Boolean electricalConductivity
    Boolean electricalResistivity
    Boolean evaporatorCoilTemperature
    Boolean exhaustTemperature
    Boolean fatMass
    Boolean formaldehydeLevel
    Boolean frequency
    Boolean generalPurposeValue
    Boolean heartRate
    Boolean heartRateRatio
    Boolean hotWaterTemperature
    Boolean humidity
    Boolean leadLevel
    Boolean liquidLineTemperature
    Boolean loudness
    Boolean luminance
    Boolean metabolicBasis
    Boolean methaneLevel
    Boolean moisture
    Boolean motionDirection
    Boolean muscleMass
    Boolean nitrogenDioxideLevel
    Boolean outsideTemperature
    Boolean ozoneLevel
    Boolean particulateMater10Level
    Boolean particulateMater1Level
    Boolean particulateMaterLevel
    Boolean power
    Boolean radonConcentration
    Boolean rainRate
    Boolean relativeModulation
    Boolean respiratoryRate
    Boolean returnAirTemperature
    Boolean rotation
    Boolean seismicIntensity
    Boolean seismicMagnitude
    Boolean signalStrength
    Boolean smokeDensity
    Boolean soilHumidity
    Boolean soilReactivity
    Boolean soilSalinity
    Boolean soilTemperature
    Boolean solarRadiation
    Boolean suctionLinePressure
    Boolean sulferDioxideLevel
    Boolean supplyAirTemperature
    Boolean tankCapacity
    Boolean targetTemperature
    Boolean tideLevel
    Boolean time
    Boolean ultraviolet
    Boolean velocity
    Boolean vocLevel
    Boolean voltage
    Boolean waterAcidity
    Boolean waterChlorineLevel
    Boolean waterFlow
    Boolean waterOxidationPotential
    Boolean waterPressure
    Boolean waterTemperature
    Boolean weight
}